### ISSUE TITLE
Test suite passing

### ISSUE THREAD

**Issue by esmarkowski** [forus-coop/select2-vanilla#3]
```
grunt 
```

**Comment by scarolayton** [comment]
![Image](https://github.com/user-attachments/assets/a95ad5ea-2fd4-4c99-bd79-2ab6054543e7)

**Comment by scarolayton** [comment]
![Image](https://github.com/user-attachments/assets/30315bbc-ca80-48a0-8cc5-06d95ae1d82f)

**Comment by scarolayton** [comment]
![Image](https://github.com/user-attachments/assets/35608077-e952-4110-943b-559df75eb02a)

**Comment by scarolayton** [comment]
![Image](https://github.com/user-attachments/assets/35d71293-1f87-4c79-ac21-52e6ff4328ec)
